CC := gcc-4.7
include $(GNUSTEP_MAKEFILES)/common.make
APP_NAME = windowdemo
windowdemo_HEADERS = AppController.h
windowdemo_OBJC_FILES = main.m AppController.m
windowdemo_RESOURCE_FILES =

include $(GNUSTEP_MAKEFILES)/application.make
