/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt

import kotlin.test.assertNotNull

//class AppTest {
//    @Test fun testAppHasAGreeting() {
//        val classUnderTest = App()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
//    }
//}


fun printBlock(name: String) {
    println("============ $name ============")
}
