/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt

import org.junit.jupiter.api.Test
import org.junit.platform.runner.JUnitPlatform
import org.junit.platform.suite.api.SelectPackages
import org.junit.runner.RunWith
import kotlin.test.assertNotNull

@RunWith(JUnitPlatform::class)
@SelectPackages("kt.rx")
class AppTest {
//    @Test
//    fun testAppHasAGreeting() {
//        val classUnderTest = App()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
//    }
}


fun printBlock(name: String) {
    println("============ $name ============")
}
