CC := gcc-4.7
include $(GNUSTEP_MAKEFILES)/common.make
APP_NAME = HelloWorld
HelloWorld_HEADERS = 
HelloWorld_OBJC_FILES = main.m say.m
HelloWorld_RESOURCE_FILES = 
include $(GNUSTEP_MAKEFILES)/application.make
