CC := gcc-4.7

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = objc_learn
objc_learn_OBJC_FILES = main.m Parent.m

include $(GNUSTEP_MAKEFILES)/tool.make
include $(GNUSTEP_MAKEFILES)/application.make

